cmake_minimum_required(VERSION 3.26)
# Configurando o padrão c++
set(CMAKE_CXX_STANDARD 17)

# Configurando o nome e executável do projeto
set(PROJECT_NAME "Echoes_of_Elementum")
project(${PROJECT_NAME})

find_package(SDL2 2.32.2 EXACT REQUIRED)
find_package(SDL2_image REQUIRED)
find_package(SDL2_ttf REQUIRED)
find_package(SDL2_mixer REQUIRED)

find_package(OpenGL REQUIRED)

set(GLEW_INCLUDE_DIRS "C:/Arquivos de Programas/Glew/include")
set(GLEW_LIBRARIES "C:/Arquivos de Programas/Glew/lib/Release/x64/glew32.lib")
include_directories(${GLEW_INCLUDE_DIRS})
link_libraries(${GLEW_LIBRARIES})

add_executable(${PROJECT_NAME}
        Source/Main.cpp
        Source/Math.cpp
        Source/Random.cpp
        Source/Actors/Actor.cpp
        Source/Components/Component.cpp
        Source/Game.cpp
        Source/Components/RigidBodyComponent.cpp
        Source/Components/RigidBodyComponent.h
        Source/Components/CircleColliderComponent.cpp
        Source/Components/CircleColliderComponent.h
        Source/Actors/Particle.cpp
        Source/Actors/Particle.h
        Source/Actors/ParticleSystem.cpp
        Source/Actors/ParticleSystem.h
        Source/Actors/Player.cpp
        Source/Actors/Player.h
        Source/Components/AABBComponent.cpp
        Source/Components/AABBComponent.h
        Source/Actors/Ground.cpp
        Source/Actors/Ground.h
        Source/Camera.cpp
        Source/Camera.h
        Source/Components/DashComponent.cpp
        Source/Components/DashComponent.h
        Source/Actors/Sword.cpp
        Source/Actors/Sword.h
        Source/Actors/FireBall.cpp
        Source/Actors/FireBall.h
        Source/Actors/Enemies/EnemySimple.cpp
        Source/Actors/Enemies/EnemySimple.h
        Source/Actors/Enemies/Enemy.cpp
        Source/Actors/Enemies/Enemy.h
        Source/Actors/Enemies/FlyingEnemySimple.cpp
        Source/Actors/Enemies/FlyingEnemySimple.h
        Source/Json.h
        Source/CSV.h
        Source/Actors/Enemies/Fox.cpp
        Source/Actors/Enemies/Fox.h
        Source/Actors/Trigger.cpp
        Source/Actors/Trigger.h
        Source/Actors/DynamicGround.cpp
        Source/Actors/DynamicGround.h
        Source/Actors/Lever.cpp
        Source/Actors/Lever.h
        Source/Actors/Effect.cpp
        Source/Actors/Effect.h
        Source/Actors/Enemies/Frog.cpp
        Source/Actors/Enemies/Frog.h
        Source/Actors/FrogTongue.cpp
        Source/Actors/FrogTongue.h
        Source/AudioSystem.cpp
        Source/AudioSystem.h
        Source/Actors/Enemies/FlyingShooterEnemy.cpp
        Source/Actors/Enemies/FlyingShooterEnemy.h
        Source/Actors/Projectile.cpp
        Source/Actors/Projectile.h
        Source/UIElements/UIScreen.h
        Source/UIElements/UIScreen.cpp
        Source/UIElements/UIFont.h
        Source/UIElements/UIFont.cpp
        Source/UIElements/UIButton.cpp
        Source/UIElements/UIButton.h
        Source/UIElements/UIText.cpp
        Source/UIElements/UIText.h
        Source/UIElements/UIElement.cpp
        Source/UIElements/UIElement.h
        Source/UIElements/UIImage.cpp
        Source/UIElements/UIImage.h
        Source/HUD.cpp
        Source/Actors/Money.cpp
        Source/Actors/Money.h
        Source/Actors/Checkpoint.cpp
        Source/Actors/Checkpoint.h
        Source/Actors/Enemies/Mantis.cpp
        Source/Actors/Enemies/Mantis.h
        Source/Actors/Enemies/Moth.cpp
        Source/Actors/Enemies/Moth.h
        Source/Actors/Enemies/Golem.cpp
        Source/Actors/Enemies/Golem.h
        Source/Actors/Skill.cpp
        Source/Actors/Skill.h
        Source/Actors/Fairy.cpp
        Source/Actors/Fairy.h
        Source/DialogueSystem.cpp
        Source/DialogueSystem.h
        Source/Cutscene.cpp
        Source/Cutscene.h
        Source/Actors/Enemies/BushMonster.cpp
        Source/Actors/Enemies/BushMonster.h
        Source/Actors/HookPoint.cpp
        Source/Actors/HookPoint.h
        Source/Actors/Enemies/FlyingGolem.cpp
        Source/Actors/Enemies/FlyingGolem.h
        Source/Actors/Enemies/DragonFly.cpp
        Source/Actors/Enemies/DragonFly.h
        Source/Components/ColliderComponent.cpp
        Source/Components/ColliderComponent.h
        Source/Components/OBBComponent.cpp
        Source/Components/OBBComponent.h
        Source/WaveManager.cpp
        Source/WaveManager.h
        Source/Actors/Lava.cpp
        Source/Actors/Lava.h
        Source/Actors/JumpEffect.cpp
        Source/Actors/JumpEffect.h
        Source/Actors/Enemies/HookEnemy.cpp
        Source/Actors/Enemies/HookEnemy.h
        Source/Actors/Spawner.cpp
        Source/Actors/Spawner.h
        Source/Actors/Enemies/FlyingSpawnerEnemy.cpp
        Source/Actors/Enemies/FlyingSpawnerEnemy.h
        Source/Actors/Enemies/LittleBat.cpp
        Source/Actors/Enemies/LittleBat.h
        Source/SaveData.cpp
        Source/SaveData.h
        Source/SaveManager.cpp
        Source/SaveManager.h
        Source/Actors/Decorations.cpp
        Source/Actors/Decorations.h
        Source/Actors/Enemies/Snake.cpp
        Source/Actors/Enemies/Snake.h
        Source/Actors/Enemies/Mushroom.cpp
        Source/Actors/Enemies/Mushroom.h
        Source/Actors/Enemies/CloneEnemy.cpp
        Source/Actors/Enemies/CloneEnemy.h
        Source/Actors/Enemies/MirrorBoss.cpp
        Source/Actors/Enemies/MirrorBoss.h
        Source/Actors/Light.cpp
        Source/Actors/Light.h
        Source/Renderer/Renderer.cpp
        Source/Renderer/Renderer.h
        Source/Renderer/VertexArray.h
        Source/Renderer/VertexArray.cpp
        Source/Renderer/Texture.cpp
        Source/Renderer/Texture.h
        Source/Renderer/Shader.cpp
        Source/Renderer/Shader.h
        Source/Components/Drawing/DrawComponent.cpp
        Source/Components/Drawing/DrawComponent.h
        Source/Components/Drawing/AnimatorComponent.cpp
        Source/Components/Drawing/AnimatorComponent.h
        Source/Components/Drawing/RectComponent.cpp
        Source/Components/Drawing/RectComponent.h
        Source/Components/Drawing/TileMapComponent.cpp
        Source/Components/Drawing/TileMapComponent.h
        Source/Actors/Brazier.cpp
        Source/Actors/Brazier.h
        Source/Components/Drawing/DrawRopeComponent.cpp
        Source/Components/Drawing/DrawRopeComponent.h
        Source/RadialMenu.cpp
        Source/RadialMenu.h
        Source/Actors/PillarGround.cpp
        Source/Actors/PillarGround.h
        Source/Actors/LightningBarrier.cpp
        Source/Actors/LightningBarrier.h
        Source/Actors/DashEffect.cpp
        Source/Actors/DashEffect.h
        Source/Actors/GroundSlamImpactEffect.cpp
        Source/Actors/GroundSlamImpactEffect.h
        Source/Actors/AirGlideEffect.cpp
        Source/Actors/AirGlideEffect.h
        Source/Components/CombatBoxComponent.cpp
        Source/Components/CombatBoxComponent.h
        Source/Actors/Enemies/OrangeSlime.cpp
        Source/Actors/Enemies/OrangeSlime.h
        Source/UIElements/UISlider.cpp
        Source/UIElements/UISlider.h
        Source/Actors/FireWisp.cpp
        Source/Actors/FireWisp.h
        Source/UIScreens/PauseMenu.cpp
        Source/UIScreens/PauseMenu.h
        Source/UIScreens/MainMenu.cpp
        Source/UIScreens/MainMenu.h
        Source/UIScreens/SelectProfileMenu.cpp
        Source/UIScreens/SelectProfileMenu.h
        Source/UIScreens/OptionsMenu.cpp
        Source/UIScreens/OptionsMenu.h
        Source/UIScreens/VideoMenu.cpp
        Source/UIScreens/VideoMenu.h
        Source/UIScreens/ConfirmBackToMenu.cpp
        Source/UIScreens/ConfirmBackToMenu.h
        Source/UIScreens/ConfirmQuitGame.cpp
        Source/UIScreens/ConfirmQuitGame.h
        Source/UIScreens/KeyboardMenu.cpp
        Source/UIScreens/KeyboardMenu.h
        Source/UIScreens/AudioMenu.cpp
        Source/UIScreens/AudioMenu.h
        Source/UIScreens/ControlMenu.cpp
        Source/UIScreens/ControlMenu.h
        Source/UIScreens/DeleteProfileMenu.cpp
        Source/UIScreens/DeleteProfileMenu.h
        Source/Components/Drawing/LightningDrawComponent.cpp
        Source/Components/Drawing/LightningDrawComponent.h
        Source/Actors/LightningEffect.cpp
        Source/Actors/LightningEffect.h
        Source/Components/Drawing/GhostTrailComponent.cpp
        Source/Components/Drawing/GhostTrailComponent.h
        Source/Actors/LightningSpear.cpp
        Source/Actors/LightningSpear.h
        Source/UIScreens/RemapControllerMenu.cpp
        Source/UIScreens/RemapControllerMenu.h
        Source/UIScreens/ResolutionMenu.cpp
        Source/UIScreens/ResolutionMenu.h
        Source/Actors/Enemies/Bat.cpp
        Source/Actors/Enemies/Bat.h
        Source/Actors/Laser.cpp
        Source/Actors/Laser.h
        Source/Actors/Enemies/StoneGolem.cpp
        Source/Actors/Enemies/StoneGolem.h
        Source/Actors/GolemProjectile.cpp
        Source/Actors/GolemProjectile.h
        Source/Actors/LaserExplosion.cpp
        Source/Actors/LaserExplosion.h
        Source/Actors/LaserShooter.cpp
        Source/Actors/LaserShooter.h
        Source/UIScreens/CheckPointMenu.cpp
        Source/UIScreens/CheckPointMenu.h
        Source/UIScreens/SkillMenu.cpp
        Source/UIScreens/SkillMenu.h
        Source/PlayerSkillManager.cpp
        Source/PlayerSkillManager.h
        Source/SkillTreeManager.cpp
        Source/SkillTreeManager.h
        Source/UIElements/UISkillNodeButton.cpp
        Source/UIElements/UISkillNodeButton.h
        Source/Actors/VineRope.cpp
        Source/Actors/VineRope.h
        Source/Actors/AmbientParticleArea.cpp
        Source/Actors/AmbientParticleArea.h
        Source/Actors/Enemies/Frogger.cpp
        Source/Actors/Enemies/Frogger.h
        Source/IconDictionary.h
        Source/MapManager.cpp
        Source/MapManager.h
        Source/UIScreens/MapMenu.cpp
        Source/UIScreens/MapMenu.h
        Source/UIScreens/NewSkillMenu.cpp
        Source/UIScreens/NewSkillMenu.h
        Source/UIScreens/AdvancedModeMenu.cpp
        Source/UIScreens/AdvancedModeMenu.h
        Source/UIScreens/ScenarioSelectorMenu.cpp
        Source/UIScreens/ScenarioSelectorMenu.h
        Source/UIScreens/PauseAdvancedMenu.cpp
        Source/UIScreens/PauseAdvancedMenu.h
        Source/UIScreens/ThankYouScreen.cpp
        Source/UIScreens/ThankYouScreen.h
)


#target_link_libraries(${PROJECT_NAME} ${SDL2_LIBRARIES})
#target_link_libraries(${PROJECT_NAME} PRIVATE SDL2::SDL2 SDL2_image::SDL2_image)
target_link_libraries(${PROJECT_NAME} PRIVATE ${GLEW_LIBRARIES} SDL2::SDL2 SDL2_image::SDL2_image SDL2_ttf::SDL2_ttf SDL2_mixer::SDL2_mixer OpenGL::GL)
